theme: jekyll-theme-modernist
title: AC299R Research Website
description: Neural Networks for Differential Equations
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
