theme: jekyll-theme-modernist
title: AC299R Research Website
description: Solutions of Differential Equations with Neural Networks
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
