theme: jekyll-theme-modernist
title: AC299R Research Website
description: Learning Closed-Form (Neural-Net) Solutions
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
